name: Rust CI

on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:
    branches:
      - main
      - 'release/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt,clippy

      - name: Cache cargo
        uses: actions/cache@v3
        with:
            path: |
                ~/.cargo/registry
                ~/.cargo/git
            key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
            restore-keys: |
                ${{ runner.os }}-cargo-


      - name: Cache build output
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Run Clippy (warnings allowed)
        run: cargo clippy --all-targets --all-features

      - name: Run tests
        run: cargo test --all --verbose

      - name: Build project
        run: cargo build --all --verbose
